# Generated by Django 5.1.2 on 2024-12-25 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_user_theme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='amount_paid',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='approved_by',
        ),
    ]
