# Generated by Django 5.1.2 on 2025-01-02 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_participant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='payment_proof',
        ),
        migrations.AddField(
            model_name='membership',
            name='payment_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='payment_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
